# frozen_string_literal: true

require 'pathname'
require 'csv'

require_relative 'lib/cwltest'
require_relative 'lib/chr_region'
require_relative 'lib/mutation_map'
require_relative 'lib/simulate/tumor_bamtofastq'
require_relative 'lib/simulate/bwa_alignment'
require_relative 'lib/simulate/mutation_call_with_normal_without_control'
require_relative 'lib/simulate/mutation_call_without_normal_without_control'

bamtofastq_test = Simulate::TumorBAMToFASTQ.new

alignment_tests = [
  Simulate::BWAAlignmentTumor.new(bamtofastq_test),
  Simulate::BWAAlignmentNormal.new(bamtofastq_test)
]

Simulate::MutationCallWithNormalWithoutControl.new(alignment_tests)
Simulate::MutationCallWithoutNormalWithoutControl.new(alignment_tests)
