# frozen_string_literal: true

require 'rake/clean'
require 'yaml'
require 'stringio'

CWLS = Dir['../Workflows/*.cwl'].sort.freeze
RSTS = ['workflows.rst'].freeze
CLOBBER.include(RSTS)

# @param str   [String] heading
# @param punct [String] single-character for punctuation
# @return      [String]
def rst_heading(str, punct)
  <<~HEADING
    #{str}
    #{punct * str.length}

  HEADING
end

# @param str [String] heading
# @return    [String]
def rst_section(str)
  rst_heading(str, '=')
end

# @param str [String] heading
# @return    [String]
def rst_subsection(str)
  rst_heading(str, '-')  
end

# @param str [String] heading
# @return    [String]
def rst_subsubsection(str)
  rst_heading(str, '^')  
end

# @param hash [Hash]
# @return     [Hash]
def deep_transform_values(hash, &block)
  hash.map.to_h do |k, v|
    [k, v.is_a?(Hash) ? deep_transform_values(v, &block) : (yield v)]
  end
end

# @param cwl [hash] CWL hash
# @return    [hash]
def resolve_namespace(cwl)
  namespaces = cwl.delete('$namespaces')
  return cwl unless namespaces

  namespaces.each do |ns_k, ns_v|
    cwl = deep_transform_values(cwl) do |v|
      r = Regexp.compile("#{ns_k}:")
      v.is_a?(String) ? v.gsub(r, ns_v) : v
    end
  end

  cwl
end

# @param uri [String]
# @return    [String]
def edam_format(uri)
  
end

# @param params [Hash] inputs/outputs part of CWL hash
def table(params)
  sio = StringIO.new

  sio.puts <<~LINE
    .. list-table::
      :header-rows: 1

      * - ID
        - Description
  LINE

  params.each do |id, val|
    sio.puts "  * - #{id}"
    sio.puts "  * - #{edam_format(val['format'])}"
    sio.puts "    - #{val['label']}"
  end

  sio.puts

  sio.string
end

# Generates ReST document from workflow CWL
# @param path [String] CWL path
# @return     [String] workflow specification ReST
def specification_rst_from_workflow_cwl(path)
  sio = StringIO.new
  cwl = resolve_namespace(YAML.load_file(path))

  sio.puts rst_subsection(cwl['id'])

  sio.puts cwl['label'] 
  sio.puts

  sio.puts rst_subsubsection('input parameters')
  sio.puts table(cwl['inputs'])

  sio.puts rst_subsubsection('output parameters')
  sio.puts table(cwl['outputs'])

  sio.string
end

file 'workflows.rst' => CWLS do |t|
  warn "generating #{t.name}"
  File.open(t.name, 'w') do |f|
    f.puts rst_section('Workflows')
    f.puts

    t.prerequisites.each do |path|
      warn "loading #{path}"
      f.puts specification_rst_from_workflow_cwl(path)
    end
  end
  warn 'done'
end

desc 'build all'
task :all => RSTS
